-- DELETE FROM student;
INSERT INTO student (name, age) VALUES ('Nathan', 23);
INSERT INTO student (name, age) VALUES ('Théo', 20);
INSERT INTO student (name, age) VALUES ('Jeanne', 40);
INSERT INTO student (name, age) VALUES ('Sebastien', 35);
INSERT INTO student (name, age) VALUES ('Pauline', 52);
INSERT INTO student (name, age) VALUES ('Marie', 18);
INSERT INTO student (name, age) VALUES ('Julie', 25);
INSERT INTO student (name, age) VALUES ('Pierre', 30);
INSERT INTO student (name, age) VALUES ('Luc', 45);
INSERT INTO student (name, age) VALUES ('Marion', 60);
INSERT INTO student (name, age) VALUES ('Alexandre', 28);
INSERT INTO student (name, age) VALUES ('Céline', 33);
