-- DELETE FROM student;
INSERT INTO student (name, age) VALUES ('Nathan', 23);
INSERT INTO student (name, age) VALUES ('Théo', 20);
INSERT INTO student (name, age) VALUES ('Jeanne', 40);
INSERT INTO student (name, age) VALUES ('Sebastien', 35);
INSERT INTO student (name, age) VALUES ('Pauline', 29);
INSERT INTO student (name, age) VALUES ('Jason', 22);
INSERT INTO student (name, age) VALUES ('Arnold', 21);
INSERT INTO student (name, age) VALUES ('Paul', 19);
INSERT INTO student (name, age) VALUES ('Riccardo', 23);